faker.version=1.0.2
loki-logback-appender.version=2.0.3
logstash-logback-encoder.version=9.0
mapstruct-processor.version=1.6.3
mapstruct.version=1.6.3
mockwebserver.version=4.12.0
snakeyaml.version=2.4
springdoc-openapi-starter-webflux-ui.version=2.8.16
testcontainers-junit-jupiter.version=1.19.0

group=ru.individuals.api
version=0.0.1-SNAPSHOT
