server:
  port: 8081

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/my-realm
  application:
    name: individuals-api

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, prometheus, info
  metrics:
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true

keycloak:
  realm: ${KEYCLOAK_REALM:my-realm}
  client-id: ${KEYCLOAK_CLIENT_ID:my-client-id}
  admin-username: ${KEYCLOAK_ADMIN_USERNAME:admin}
  admin-password: ${KEYCLOAK_ADMIN_PASSWORD:password}

logging:
  level:
    org:
      springframework: INFO