spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://keycloak:8080/realms/my-realm}

keycloak:
  base-url: ${KEYCLOAK_BASE_URL:http://keycloak:8080}

logging:
  loki:
    url: ${LOKI_URL:http://loki:3100/loki/api/v1/push}